/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#313031",
        "surface-container-low": "#191c1e",
        "secondary-fixed": "#e5e2e3",
        "on-tertiary-fixed-variant": "#474649",
        "on-secondary-container": "#bab8b9",
        "on-background": "#e0e3e5",
        "secondary-container": "#4a494a",
        "on-primary": "#490080",
        "inverse-on-surface": "#2d3133",
        "on-primary-container": "#400071",
        "primary-fixed-dim": "#ddb7ff",
        "on-tertiary-fixed": "#1b1b1d",
        "on-surface": "#e0e3e5",
        "error-container": "#93000a",
        "secondary": "#c8c6c7",
        "error": "#ffb4ab",
        "tertiary-container": "#929092",
        "on-tertiary": "#303032",
        "surface-variant": "#323537",
        "tertiary-fixed-dim": "#c8c6c8",
        "primary-fixed": "#f0dbff",
        "on-primary-fixed": "#2c0051",
        "inverse-surface": "#e0e3e5",
        "surface-tint": "#ddb7ff",
        "primary": "#ddb7ff",
        "tertiary": "#c8c6c8",
        "on-error": "#690005",
        "on-tertiary-container": "#2a292b",
        "surface-container-lowest": "#0b0f10",
        "on-secondary-fixed": "#1c1b1c",
        "secondary-fixed-dim": "#c8c6c7",
        "surface-container": "#1d2022",
        "on-surface-variant": "#cfc2d6",
        "on-primary-fixed-variant": "#6900b3",
        "on-secondary-fixed-variant": "#474647",
        "primary-container": "#b76dff",
        "surface-bright": "#363a3b",
        "tertiary-fixed": "#e4e2e4",
        "outline": "#988d9f",
        "surface-dim": "#101415",
        "surface": "#101415",
        "outline-variant": "#4d4354",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#842bd2",
        "surface-container-highest": "#323537",
        "surface-container-high": "#272a2c",
        "background": "#101415"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "container-max": "1440px",
        "unit": "8px",
        "gutter": "24px"
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "title-md": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
        "headline-xl": ["Montserrat", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"]
      },
      transitionTimingFunction: {
        'apple': 'cubic-bezier(0.22, 1, 0.36, 1)',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in-down': {
          '0%': { opacity: '0', transform: 'translateY(-12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'zoom-in': {
          '0%': { opacity: '0', transform: 'scale(0.97)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'modal-in': {
          '0%': { opacity: '0', transform: 'scale(0.94)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.3s cubic-bezier(0.22, 1, 0.36, 1) forwards',
        'fade-in-up': 'fade-in-up 0.4s cubic-bezier(0.22, 1, 0.36, 1) forwards',
        'fade-in-down': 'fade-in-down 0.4s cubic-bezier(0.22, 1, 0.36, 1) forwards',
        'zoom-in': 'zoom-in 0.4s cubic-bezier(0.22, 1, 0.36, 1) forwards',
        'modal-in': 'modal-in 0.3s cubic-bezier(0.22, 1, 0.36, 1) forwards',
      },
    },
  },
  plugins: [],
};
